@Library ('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('conti-down')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/intelliq-it/maven.git")
                }
            }
        }
        stage('conti-build')
        {
            steps
            {
                script
                {
                    cicd.newmaven()
                }
            }
        }
        stage('conti-deploy')
        {
            steps
            {
                script
                {
                    cicd.newdeploy("sharedlibrarywithdeclarativepipeline","172.31.87.17","qaapp")
                }
            }
        }
        stage('conti-testing')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/intelliq-it/funtionalTesting.git")
                    cicd.runselenium("sharedlibrarywithdeclarativepipeline")
                }
            }
        }
        stage('conti-delivery')
        {
            steps
            {
                script
                {
                     cicd.newdeploy("sharedlibrarywithdeclarativepipeline","172.31.88.129","prodapp")
                }
            }
        }
    }
}
    
